version: 0.0
os: linux
files:
  - source: /dist/
    destination: /usr/share/nginx/html/
    overwrite: yes
file_exists_bihavior: OVERWRITE
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root