version: 0.0
os: linux
files:
  - source: /stupidscore-pipeline/SourceArti/
    destination: /usr/share/nginx/html/
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root