version: 0.0
os: linux
files:
  - source: /dist/
    destination: /usr/share/nginx/html/
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user